## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false
git:
  depth: 99999999

branches:
  only:
    - master
    - /release-.*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

# uncomment the following lines to override the default test script
script:
 - julia -e 'using Pkg; Pkg.activate(pwd()); pkg"instantiate"; pkg"add https://github.com/jagot/OrthoPoly.jl.git"'
 - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
