environment:
  matrix:
  - julia_version: 1.1
  - julia_version: 1.2
  - julia_version: 1.3
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

branches:
  only:
    - master
    - /release-.*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "using Pkg; Pkg.activate(pwd()); pkg\"instantiate\"; pkg\"add https://github.com/jagot/OrthoPoly.jl.git\""
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
